version: 5
settings:
  hack: true
  config:
    disabled: false
  log:
    level: info
  commit:
    key:
      enabled: true
      required: true
      prompt:
        select:
          page: 5
          suggestion: false
          values:
            - key: feat
              text: Introducing new features
            - key: perf
              text: Improving user experience / usability / reliablity
            - key: fix
              text: Fixing a bug
            - key: chore
              text: Other changes unrelated to user/client
    scope:
      enabled: true
      required: false
      prompt:
        select:
          page: 5
          suggestion: false
          values:
            - key: shared
              text: Shared library
            - key: gen
              text: Generator repository
            - key: metric
              text: Metric repository
            - key: scripts
              text: Helpers scripts
            - key: deps
              text: Development dependencies
            - key: docs
              text: Documentation
    title:
      enabled: true
      required: true
      prompt:
        input:
          max: 75
          multiline: false
    message:
      enabled: false
      required: false
      prompt:
        input:
          max: 200
          multiline: true
