name: Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1" # https://crontab.guru/#0_5_*_*_1

jobs:
  changelog:
    name: "Changelog"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install git-chglog
        run: go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
      - name: Version
        run: |
          gh --version
          git-chglog --version
      - name: Login to Github
        run: |
          gh auth status
      - name: Generate changelog
        run: git-chglog --output CHANGELOG.md
      - name: Setup git
        run: |
          git config --global user.name 'Github Action Generator'
          git config --global user.email 'personal@kamontat.net'
      - name: Commit and create PR
        run: |
          git checkout -b "release/$(date +'%y%m%d')"
          git commit -am "chore: auto generate changelog [skip-ci]"
          gh pr create --title "chore: release note ($(date +'%y%m%d'))" --label "release-note" --fill
