name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Enable Docker Experimental
        run: |
          cat "/etc/docker/daemon.json"

          mkdir -p ~/.docker

          echo $'{"cgroup-parent": "/actions_job","experimental": true}' | sudo tee /etc/docker/daemon.json
          echo $'{"experimental": "enabled"}' | sudo tee ~/.docker/config.json

          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker version -f '{{.Server.Experimental}}'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Tidy module in generator
        working-directory: generator
        run: go mod tidy
      - name: Tidy module in metric
        working-directory: metric
        run: go mod tidy
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
