name: unittest

on:
  push:
    branches:
      - '**'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: unittest on shared
        working-directory: shared
        run: |
          go mod tidy
          go test ./...
      - name: unittest on generator
        working-directory: generator
        run: |
          go mod tidy
          go test ./...
      - name: unittest on metric
        working-directory: metric
        run: |
          go mod tidy
          go test ./...
